const cinemas = [
  {
    name: 'Genesis, Abuja, Ceddi Plaza',
    address: 'Ceddi Plaza, Abuja',
    capacity: 300,
    state: 'Abuja',
  },
]
'Genesis Abuja, Gateway Mall',
  'Genesis, Port Harcourt',
  'CARTEGE CINEMAS, ASABA',
  'Genesis, Palms, Lekki',
  'Genesis, Maryland',
  'Genesis, Owerri',
  'Viva Cinemas Enugu',
  'Viva Cinemas Ilorin',
  'Viva Cinema Ibadan',
  'Viva Cinemas Ota',
  'Genesis Novare Mall, Ajah',
  'SKY CINEMAS SANGOTEDO',
  'OOPL Cinemas, Abeokuta',
  'Viva Cinema Ikeja',
  'KADA CINEMAS BENIN',
  'MEGA 1 CINEMAS',
  '7eleven Drive-In Cinema, Union Bank Sports Club, 41 Bode Thomas, Surulere, Lagos'
